# admier

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: fpm
spec:
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: fpm
spec:
  selector:
    app: adminer
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31080
