# for mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlserver
  namespace: fpm
spec:
  selector:
    matchLabels:
      app: mysqlserver
  template:
    metadata:
      labels:
        app: mysqlserver
    spec:
      containers:
      - name: mysqlserver
        image: mysql:5.6
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "741235896"

---
apiVersion: v1
kind: Service
metadata:
  name: mysqlserver
  namespace: fpm
spec:
  type: NodePort
  selector:
    app: mysqlserver
  ports:
    - targetPort: 3306
      port: 3306


# for redis
# deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisserver
  namespace: fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redisserver
        image: redis:alpine3.11
        ports:
          - containerPort: 6379

# for redis server
# deployment
---
apiVersion: v1
kind: Service
metadata:
  name: redisserver
  namespace: fpm
spec:
  selector:
    app: redis
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379


# for pg
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgserver
  namespace: fpm
spec:
  selector:
    matchLabels:
      app: pgserver
  template:
    metadata:
      labels:
        app: pgserver
    spec:
      containers:
      - name: pgserver
        image: postgres:13-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: POSTGRES_DB
          value: fpmiot
        - name: POSTGRES_PASSWORD
          value: Fpm741235896
# pgserver service
---
apiVersion: v1
kind: Service
metadata:
  name: pgserver
  namespace: fpm
spec:
  selector:
    app: pgserver
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
